#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 
ip link set lo up || true

getty 0 tty1 &
getty 0 tty2 &
getty 0 tty3 &

exec setsid /bin/sh </dev/tty2 >/dev/tty2 2>&1
