#!/bin/sh

set -e

mount -t proc proc /proc 2>/dev/null || true
mount -t sysfs sysfs /sys 2>/dev/null || true
mount -t devtmpfs devtmpfs /dev 2>/dev/null || true
mount -t tmpfs tmpfs /run 2>/dev/null || true

while true; do /bin/sh </dev/tty1 >/dev/tty1 2>&1; done
