#!/bin/sh

MODULES_FILE="/etc/modules"

[ ! -r "${MODULES_FILE}" ] && exit 0

load_unload() {
  while read -r module args; do
    case "$module" in
      ""|"#"*) continue ;;
    esac
    if [ "$1" = "load" ]; then
      modprobe -q "${module}" ${args} >/dev/null && \
      printf '%s ' "$module" || RET='FAIL'
    else
      rmmod "${module}" >/dev/null 2>&1 || RET='FAIL'
    fi
  done < "${MODULES_FILE}"
  RET='OK'
}

start() {
  printf 'Starting modules: '
  load_unload load
  echo "$RET"
}

stop() {
  printf 'Stopping modules: '
  load_unload unload
  echo "$RET"
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start|stop|restart)
    "$1";;
  reload)
    restart;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac
